# Generated by Django 3.1.2 on 2020-11-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, verbose_name='Employee Id')),
                ('employee_name', models.CharField(max_length=25, verbose_name='Employee Name')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='News Title')),
                ('place', models.CharField(max_length=120, verbose_name='Place')),
                ('date', models.DateTimeField(verbose_name='Event Date and Time')),
                ('description', models.TextField(verbose_name='Details')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Picture')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counterapp.category')),
            ],
        ),
    ]
