# Generated by Django 3.1.2 on 2020-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='News Title')),
                ('author', models.CharField(max_length=120, verbose_name='Author')),
                ('place', models.CharField(max_length=120, verbose_name='Place')),
                ('date', models.DateTimeField(verbose_name='Event Date and Time')),
                ('description', models.TextField(verbose_name='Details')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Picture')),
            ],
        ),
    ]
