# Generated by Django 3.1.2 on 2020-11-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0002_auto_20201030_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
