# Generated by Django 3.1.2 on 2020-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, verbose_name='Employee Id')),
                ('employee_name', models.CharField(max_length=25, verbose_name='Employee Name')),
            ],
        ),
    ]
